for uploading huge amount of data from kaggle to google collab we use api token from kaggle and copy the code in google collab.

In [2]:
#creating numpy/nd arrays
import numpy as np


In [3]:
# Creating 1d array
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [6]:
#To check the data type
type(arr1)

#to check the dimensions of array
arr1.ndim


2

In [8]:

# Creating 2-d arrays
arr2=np.array([[1,2,3],[4,5,6]])
arr2.ndim

2

In [7]:

# Creating 2-d arrays
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
#Creates matrix of given order with all elements as zeros
arr3=np.zeros((2,3))
arr3

2

In [12]:
#Creates matrix of given order with all elements as ones
arr3=np.ones((3,4))
arr3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
#Creates identity matrix of order 5
arr4=np.identity(5)
arr4

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
#Creates elements of given range in function contains of 3 parameter 
# 1st and 2nd paramter is for range and third parameter is for jump check line 16
arr5=np.arange(10)
arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr5=np.arange(5,15)
arr5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
 arr6=np.arange(5,15,2)
 arr6

array([ 5,  7,  9, 11, 13])

In [18]:
#makes an array with given range which are equidistance consists of three paramenters third one is for total number in array
arr7=np.linspace(10,20,10)
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [20]:
#copies an array
arr8=arr7.copy()
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])